# Trading settings
trading:
  exchange: "binance"
  api_key: "your_binance_key"
  api_secret: "your_binance_secret"
  max_position_size: 1000.0
  risk_per_trade: 2.0

# Paths
paths:
  data: "data"
  logs: "data/logs"

# Server
server:
  host: "0.0.0.0"
  port: 8000

# Agent settings
agent:
  cycle_interval: 300  # 5 минут
  max_goals: 5
  learning_sessions_limit: 3
  advisor_threshold: 0.7
  recovery_threshold: 0.8
  recovery_max_tries: 3

# Trader settings
trader:
  cycle_interval: 600  # 10 минут
  demo_mode: true
  max_position_size: 1000.0
  stop_loss_percent: 0.02
  take_profit_percent: 0.04
  max_drawdown: 0.05
