name: CI - Tests & Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        cd mirai-agent
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-asyncio black flake8 mypy
    
    - name: Check code formatting (black)
      run: |
        cd mirai-agent
        black --check --diff core/ tests/ || echo "⚠️ Code needs formatting"
    
    - name: Lint with flake8
      run: |
        cd mirai-agent
        # Stop build if there are Python syntax errors or undefined names
        flake8 core/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 core/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Type check with mypy
      run: |
        cd mirai-agent
        mypy core/ --ignore-missing-imports --no-strict-optional || echo "⚠️ Type hints need improvement"
    
    - name: Run unit tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        cd mirai-agent
        pytest tests/unit/ -v --tb=short
    
    - name: Run integration tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        cd mirai-agent
        pytest tests/integration/ -v --tb=short || echo "⚠️ Integration tests need attention"
    
    - name: Generate coverage report
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        cd mirai-agent
        pytest tests/ --cov=core --cov-report=xml --cov-report=term
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./mirai-agent/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  health-check:
    name: Health Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        cd mirai-agent
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run health check script
      run: |
        chmod +x scripts/healthcheck.sh
        # Health check может вернуть 1 если не все зависимости
        # Но мы проверяем что скрипт запускается
        ./scripts/healthcheck.sh --verbose || echo "⚠️ Health check warnings"
    
    - name: Test core imports
      run: |
        cd mirai-agent
        python3 -c "from core.autonomous_agent import AutonomousAgent; print('✅ AutonomousAgent imports')"
        python3 -c "from core.memory_manager import MemoryManager; print('✅ MemoryManager imports')"
        python3 -c "from core.logger import setup_logger; print('✅ Logger imports')"
        python3 -c "from core.config_manager import ConfigManager; print('✅ ConfigManager imports')"
    
    - name: Validate configuration
      run: |
        cd mirai-agent
        python3 -c "
from core.config_manager import ConfigManager
config = ConfigManager()
print(f'✅ Config version: {config.get(\"version\")}')
print(f'✅ Database path: {config.get(\"database.path\")}')
"

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install safety
      run: |
        pip install safety bandit
    
    - name: Check dependencies for vulnerabilities
      run: |
        cd mirai-agent
        pip install -r requirements.txt
        safety check || echo "⚠️ Security vulnerabilities found"
    
    - name: Run bandit security scan
      run: |
        cd mirai-agent
        bandit -r core/ -ll || echo "⚠️ Security issues found"

  build-status:
    name: Build Status Summary
    runs-on: ubuntu-latest
    needs: [test, health-check, security]
    if: always()
    
    steps:
    - name: Check build status
      run: |
        echo "🎯 CI Pipeline Complete!"
        echo "Test: ${{ needs.test.result }}"
        echo "Health: ${{ needs.health-check.result }}"
        echo "Security: ${{ needs.security.result }}"
