name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements-ci.txt ]; then pip install -r requirements-ci.txt; fi

      - name: Bytecode compilation
        run: |
          python -m compileall -x path_to_your_code_file mirai-agent mirai-pro

      - name: Core integration tests
        run: |
          pytest mirai-agent/tests/integration/test_config_scenarios.py
